apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar1-deployment
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: hotstar1
  template:
    metadata:
      labels:
        app: hotstar1
    spec:
      containers:
      - name: hotstar1
        image: jayavinesh7/hotstar1:latest
        ports:
        - containerPort: 3000  # Port your application listens on
